export const HTML_QUESTIONS = [
  {
    id: 1,
    question: `1. What does HTML stand for? `,
    options: [
      "Hyper Text Makeup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
      "Hyper Text Markup Language ",
    ],
    answer: 3,
  },
  {
    id: 2,
    question: `2.	Which tag is used to create a hyperlink in HTML? `,
    options: [" <a> ", "<h1> ", "<p> ", "<img>"],
    answer: 0,
  },
  {
    id: 3,
    question: `3.	Which tag is used to define a paragraph in HTML? `,
    options: ["<a> ", "<h1> ", "<p> ", "<img> "],
    answer: 2,
  },
  {
    id: 4,
    question: `4.	Which tag is used to define a heading in HTML?`,
    options: [" <a> ", "<h1> ", "<p> ", "<img> "],
    answer: 1,
  },
  {
    id: 5,
    question: `5.	Which tag is used to add an image in HTML? `,
    options: [" <a>", "<h1>", "<p>", "<img>"],
    answer: 3,
  },
  {
    id: 6,
    question: `6.	Which tag is used to create a line break in HTML?`,
    options: [" <br> ", "<hr>", "<p>", "<img>"],
    answer: 0,
  },
  {
    id: 7,
    question: `7.	Which attribute is used to specify the alternate text for an image in HTML?`,
    options: [" alt ", "src", "href", "title"],
    answer: 0,
  },
  {
    id: 8,
    question: `8.	Which tag is used to define a list in HTML?`,
    options: [" <li> ", "<ol>", "<ul>", "<dl>"],
    answer: 1,
  },
  {
    id: 9,
    question: `9.	Which tag is used to define an unordered list in HTML?`,
    options: [" <li> ", "<ol>", "<ul>", "<dl>"],
    answer: 2,
  },
  {
    id: 10,
    question: `10.	Which tag is used to define a definition list in HTML?`,
    options: [" <li> ", "<ol>", "<ul>", "<dl>"],
    answer: 3,
  },
  {
    id: 11,
    question: `11.	Which attribute is used to set the width of a table in HTML?`,
    options: [" width ", "height", "size", "style "],
    answer: 0,
  },
  {
    id: 12,
    question: `12.	Which tag is used to define a table row in HTML?`,
    options: [" <tr> ", "<td> ", "<th>", "<table> "],
    answer: 0,
  },
  {
    id: 13,
    question: `	13.	Which tag is used to define a table cell in HTML? `,
    options: [" <tr> ", "<td> ", "<th>", "<table> "],
    answer: 1,
  },
  {
    id: 14,
    question: `	14.	Which tag is used to define a table header cell in HTML?  `,
    options: ["<tr> ", "<td> ", "<th>", "<table> "],
    answer: 2,
  },
  {
    id: 15,
    question: `	15.	Which tag is used to create a form in HTML? `,
    options: ["<form> ", "<input> ", "<label>", "<select>  "],
    answer: 0,
  },
  {
    id: 16,
    question: `	16.	Which attribute is used to specify the type of an input field in HTML?`,
    options: ["type ", "value ", "name", "action "],
    answer: 0,
  },
  {
    id: 17,
    question: `17.	Which input type is used to create a checkbox in HTML?`,
    options: ["text ", "password", "checkbox", "radio"],
    answer: 0,
  },
  {
    id: 18,
    question: `	18.	Which input type is used to create a radio button in HTML?`,
    options: ["text ", "password", "checkbox", "radio"],
    answer: 3,
  },
  {
    id: 19,
    question: `	19.	Which input type is used to create a password field in HTML?`,
    options: ["text ", "password", "checkbox", "radio"],
    answer: 1,
  },
  {
    id: 20,
    question: `20.	Which tag is used to create a dropdown list in HTML?`,
    options: [" <form> ", "<input>", "<label> ", "<select>"],
    answer: 3,
  },
  {
    id: 21,
    question: `	21.	Which attribute is used to specify the value of an input field in HTML?`,
    options: ["type ", "value", "name", "action"],
    answer: 1,
  },
  {
    id: 22,
    question: `	22.	Which attribute is used to specify the action to be performed on form submission in HTML? `,
    options: ["type ", "value", "name", "action"],
    answer: 3,
  },
  {
    id: 23,
    question: `	23.	Which tag is used to add a comment in HTML? `,
    options: [
      "<!-- comment --> ",
      "<comment>comment</comment>",
      "<p>comment</p> ",
      "<span>comment</span> ",
    ],
    answer: 0,
  },
  {
    id: 24,
    question: `24.	Which tag is used to create a horizontal rule in HTML?  `,
    options: ["<hr> ", "<br>", "<dr> ", "<p> "],
    answer: 0,
  },
  {
    id: 25,
    question: `25.	Which tag is used to add a video in HTML?  `,
    options: ["<video> ", "<audio>", "<img> ", "<object> "],
    answer: 0,
  },
  {
    id: 26,
    question: `	26.	Which tag is used to add audio in HTML?  `,
    options: ["<video> ", "<audio>", "<img> ", "<object> "],
    answer: 1,
  },
  {
    id: 27,
    question: `	27.	Which tag is used to add an iframe in HTML? `,
    options: ["<iframe> ", "<frame> ", "<embed>  ", "<object> "],
    answer: 0,
  },
  {
    id: 28,
    question: `28.	Which attribute is used to specify the source of an image or media in HTML? `,
    options: ["alt ", "src ", "href", " title "],
    answer: 1,
  },
  {
    id: 29,
    question: `	29.	Which tag is used to create a link to an external CSS file in HTML? `,
    options: ["<style> ", "<link>", "<script> ", " <meta>"],
    answer: 1,
  },
  {
    id: 30,
    question: `	31.	Which tag is used to create a meta description in HTML? `,
    options: ["<style> ", "<link>", "<script> ", " <meta>"],
    answer: 3,
  },
  {
    id: 31,
    question: `	31.	What does CSS stand for? `,
    options: [
      " Computer Style Sheets  ",
      "Creative Style Sheets ",
      "Cascading Style Sheets",
      " Colorful Style Sheets Answer",
    ],
    answer: 2,
  },
  {
    id: 32,
    question: `	33.	What is the correct CSS syntax for setting the font family of an element?  `,
    options: [
      "font-family: Arial, sans-serif;",
      "font: Arial, sans-serif; ",
      "family-font: Arial, sans-serif; ",
      "font_type: Arial, sans-serif; ",
    ],
    answer: 0,
  },
  {
    id: 33,
    question: `	33.	Which property is used to change the background color of an element in CSS?  `,
    options: ["color", "background-color", "bg-color ", " bg"],
    answer: 1,
  },
  {
    id: 34,
    question: `34.	Which property is used to set the height of an element in CSS?  `,
    options: ["height", " width ", "size ", " length "],
    answer: 0,
  },
  {
    id: 35,
    question: `35.	Which property is used to set the width of an element in CSS?  `,
    options: ["height", "width ", "size ", " length "],
    answer: 1,
  },
  {
    id: 36,
    question: `	36.	Which property is used to align text in CSS? `,
    options: ["align", "text-align ", "center ", "justify "],
    answer: 1,
  },
  {
    id: 37,
    question: `	37.	Which property is used to set the font size in CSS? `,
    options: ["font ", "size ", "font-size  ", "font-style"],
    answer: 2,
  },
  {
    id: 38,
    question: `	38.	Which property is used to make the text bold in CSS? `,
    options: ["font-weight", "bold ", " font-style ", "text-transform"],
    answer: 0,
  },
  {
    id: 39,
    question: ` 39.	Which property is used to make the text italic in CSS? `,
    options: ["font-style ", "italic ", "font-weight  ", "text-transform"],
    answer: 0,
  },
  {
    id: 40,
    question: `	40.	Which property is used to add an underline to text in CSS? `,
    options: ["underline", "text-decoration", "decoration", "line"],
    answer: 1,
  },
  {
    id: 41,
    question: `41. Which property is used to add a border to an element in CSS?`,
    options: ["border", "outline", "border-style ", "border-width"],
    answer: 0,
  },
  {
    id: 42,
    question: ` 42.	Which property is used to add padding to an element in CSS?`,
    options: ["padding ", "margin", "spacing", "border"],
    answer: 0,
  },
  {
    id: 43,
    question: `43.	Which property is used to add margin to an element in CSS?`,
    options: ["padding ", "margin", "spacing", "border"],
    answer: 1,
  },
  {
    id: 44,
    question: `	44.	Which property is used to set the position of an element in CSS?`,
    options: ["position ", "place", "location", "offset"],
    answer: 0,
  },
  {
    id: 45,
    question: `	45.	Which property is used to change the color of text in CSS?`,
    options: ["color ", "font-color ", "text-color ", "style"],
    answer: 0,
  },
  {
    id: 46,
    question: `	46.	Which property is used to set the opacity of an element in CSS?`,
    options: ["opacity", "transparency ", "filter", "visibility"],
    answer: 0,
  },
  {
    id: 47,
    question: `	47.	Which property is used to add a shadow to an element in CSS?`,
    options: ["shadow", "box-shadow", "text-shadow", "element-shadow"],
    answer: 1,
  },
  {
    id: 48,
    question: `	48.	Which property is used to make an element float in CSS?`,
    options: ["float", "position", "clear", "display"],
    answer: 0,
  },
  {
    id: 49,
    question: `	49.	Which property is used to set the text alignment in the vertical axis in CSS?`,
    options: ["vertical-align", "align", "text-align ", "line-height"],
    answer: 0,
  },
  {
    id: 50,
    question: `50.	Which property is used to display an element as a block-level element in CSS? `,
    options: [
      "display:block;",
      "display: inline;",
      "display: none;",
      "display: flex;",
    ],
    answer: 0,
  },
  {
    id: 51,
    question: `	51.	Which property is used to display an element as an inline-level element in CSS? `,
    options: [
      "display:block;",
      "display: inline;",
      "display: none;",
      "display: flex;",
    ],
    answer: 1,
  },
  {
    id: 52,
    question: `	52.	Which property is used to display an element as a flex container in CSS? `,
    options: [
      "display:block;",
      "display: inline;",
      "display: none;",
      "display: flex;",
    ],
    answer: 3,
  },
  {
    id: 53,
    question: `	53.	Which property is used to add a gradient background to an element in CSS?`,
    options: [
      "background-color",
      "background-image",
      "background-gradient ",
      "gradient-color",
    ],
    answer: 1,
  },
  {
    id: 54,
    question: `	54.	Which property is used to make an element transparent in CSS?`,
    options: ["opacity", "visibility", "filter", "transparent"],
    answer: 0,
  },
  {
    id: 55,
    question: `55.	Which property is used to change the order of elements in a flex container in CSS?`,
    options: ["order", "flex-direction", "justify-content", "align-items"],
    answer: 0,
  },
  {
    id: 56,
    question: `	56.	Which property is used to align flex items horizontally in a flex container in CSS?`,
    options: ["order", "flex-direction", "justify-content", "align-items"],
    answer: 2,
  },
  {
    id: 57,
    question: `	57.	Which property is used to align flex items vertically in a flex container in CSS?`,
    options: ["order", "flex-direction", "justify-content", "align-items"],
    answer: 3,
  },
  {
    id: 58,
    question: `	59.	Which property is used to change the flex direction of a flex container in CSS?`,
    options: ["order", "flex-direction", "justify-content", "align-items"],
    answer: 1,
  },
  {
    id: 59,
    question: `	59.	Which property is used to set the maximum width of an element in CSS?`,
    options: ["max-width", "width", "min-width", "max-width"],
    answer: 0,
  },
  {
    id: 60,
    question: `	60.	Which property is used to set the maximum height of an element in CSS? `,
    options: ["max-height", "height", "min-height", "flex-basis"],
    answer: 0,
  },
  {
    id: 61,
    question: `	61.	What is Bootstrap? `,
    options: [
      "A programming language",
      "A library for CSS and JavaScript",
      "A database management system",
      "A text editor",
    ],
    answer: 1,
  },
  {
    id: 62,
    question: `	62.	Which version of Bootstrap is the latest as of September 2021? `,
    options: ["3", "4", "5", "6"],
    answer: 2,
  },
  {
    id: 63,
    question: `63.	Which of the following is not a component in Bootstrap? `,
    options: ["Navbar", "Modal", "Carousel", "Table"],
    answer: 3,
  },
  {
    id: 64,
    question: `64.	Which class is used to create a grid system in Bootstrap? `,
    options: [".grid", ".container", ".row", ".col"],
    answer: 2,
  },
  {
    id: 65,
    question: `65. Which class is used to create a container in Bootstrap? `,
    options: [".grid", ".container", ".row", ".col"],
    answer: 1,
  },
  {
    id: 66,
    question: `66. Which class is used to create a navigation bar in Bootstrap?  `,
    options: [".navbar", ".nav", ".navbar-nav", ".nav-link "],
    answer: 0,
  },
  {
    id: 67,
    question: ` 67.	Which class is used to create a button in Bootstrap? `,
    options: [".button", ".btn", ".btn-group", ".btn-link  "],
    answer: 1,
  },
  {
    id: 68,
    question: `68.	Which class is used to create a card in Bootstrap? `,
    options: [".card", ".card-body", ".card-title", ".card-header  "],
    answer: 0,
  },
  {
    id: 69,
    question: `	69.	Which class is used to create a modal in Bootstrap? `,
    options: [".modal", " .modal-body", ".modal-header", ".modal-dialog"],
    answer: 0,
  },
  {
    id: 70,
    question: `70.	Which class is used to create a carousel in Bootstrap? `,
    options: [
      ".carousel",
      " .carousel-item ",
      ".carousel-caption",
      ".carousel-control",
    ],
    answer: 0,
  },
  {
    id: 71,
    question: `71.	Which class is used to create a form in Bootstrap? `,
    options: [".form", " .form-control ", ".form-group", ".form-check"],
    answer: 2,
  },
  {
    id: 72,
    question: `72.	Which class is used to create a jumbotron in Bootstrap? `,
    options: [
      ".jumbotron ",
      ".jumbotron-header ",
      ".jumbotron-body",
      ".jumbotron-fluid",
    ],
    answer: 0,
  },
  {
    id: 73,
    question: `73.	Which class is used to create a progress bar in Bootstrap?  `,
    options: [
      ".progress  ",
      ".progress-bar",
      ".progress-value",
      ".progress-fill ",
    ],
    answer: 1,
  },
  {
    id: 74,
    question: `	74.	Which class is used to create a dropdown menu in Bootstrap?   `,
    options: [
      ".dropdown ",
      ".dropdown-item",
      ".dropdown-menu",
      ".dropdown-toggle",
    ],
    answer: 2,
  },
  {
    id: 75,
    question: `	75.	Which class is used to create a badge in Bootstrap?`,
    options: [".badge", ".badge-item", ".badge-text", ".badge-label"],
    answer: 0,
  },
  {
    id: 76,
    question: `	76.	Which class is used to create a tooltip in Bootstrap?`,
    options: [
      ".tooltip",
      ".tooltip-text",
      ".tooltip-label ",
      ".tooltip-title ",
    ],
    answer: 0,
  },
  {
    id: 77,
    question: `	77.	Which class is used to create a popover in Bootstrap?`,
    options: [
      ".popover ",
      ".popover-body",
      ".popover-header  ",
      ".popover-title  ",
    ],
    answer: 0,
  },
  {
    id: 78,
    question: `	78.	Which class is used to create a list group in Bootstrap?`,
    options: [".list-group", ".list-item ", ".list-group-item", ".list-text"],
    answer: 2,
  },
  {
    id: 79,
    question: `	79.	Which class is used to create a pill navigation in Bootstrap?`,
    options: [".pill-nav", ".nav-pills ", ".nav-item-pills", ".nav-link-pills"],
    answer: 1,
  },
  {
    id: 80,
    question: `	80.	Which class is used to create a collapse component in Bootstrap? `,
    options: [
      ".collapse ",
      ".collapse-content ",
      ".collapse-header",
      ".collapse-body",
    ],
    answer: 0,
  },
  {
    id: 81,
    question: `	81.	Which class is used to create a breadcrumb navigation in Bootstrap? `,
    options: [
      ".breadcrumb  ",
      ".breadcrumb-nav ",
      ".breadcrumb-item ",
      ".breadcrumb-link ",
    ],
    answer: 0,
  },
  {
    id: 82,
    question: `	82.	Which class is used to create a media object in Bootstrap?`,
    options: [".media ", ".media-object ", ".media-body ", ".media-content "],
    answer: 0,
  },
  {
    id: 83,
    question: `	83.	Which class is used to create a list of horizontal links in Bootstrap? `,
    options: [
      ".list-horizontal ",
      ".horizontal-links  ",
      ".nav-horizontal ",
      ".nav-tabs",
    ],
    answer: 3,
  },
  {
    id: 84,
    question: `	84.	Which class is used to create a responsive embed in Bootstrap?  `,
    options: [
      ".embed-responsive ",
      ".responsive-embed  ",
      ".video-responsive ",
      ".responsive-video",
    ],
    answer: 0,
  },
  {
    id: 85,
    question: `	85.	Which class is used to create a spinner in Bootstrap? `,
    options: [
      ".spinner",
      ".spinner-item ",
      ".spinner-grow ",
      ".spinner-circle ",
    ],
    answer: 2,
  },
  {
    id: 86,
    question: `	86.	Which class is used to create a toast message in Bootstrap? `,
    options: [".toast", ".toast-header ", ".toast-body ", ".toast-message "],
    answer: 0,
  },
  {
    id: 87,
    question: `	87.	Which class is used to create a container that spans the full width of the viewport in Bootstrap 5? `,
    options: [
      ".container-fluid",
      ".container-full",
      ".container-wide ",
      ".container-viewport ",
    ],
    answer: 0,
  },
  {
    id: 88,
    question: `	88. Which class is used to create a responsive grid that adjusts based on the size of the viewport? `,
    options: [
      ".grid-responsive",
      ".responsive-grid ",
      ".grid-fluid ",
      ".grid-container",
    ],
    answer: 1,
  },
  {
    id: 89,
    question: `89.	90.	Which class is used to create a scrollspy component in Bootstrap?  `,
    options: [".scrollspy", ".spy-scroll ", ".spy-target ", ".scrollspy"],
    answer: 1,
  },
  {
    id: 90,
    question: `90.	Which class is used to create a floating action button in Bootstrap?  `,
    options: [".fab", ".floating-action-button ", ".fab-button ", ".fab-icon"],
    answer: 1,
  },
];
